
version: 2

sources:
  - name: erpadventureworks
    tables:
      - name: salesorderdetail
      - name: product
      - name: address
      - name: countryregion
      - name: person
      - name: stateprovince
      - name: creditcard
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: customer